repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.5
    hooks:
      - id: pylint

  - repo: local
    hooks:
      - id: bible-checker
        name: bible-checker
        entry: bash -c 'echo "(placeholder) biblia checks"'
        language: system
        files: ''
